---
title: "Nuevo"
output: html_document
date: '2022-07-15'
---

```{r}
library(tidyverse)
library(patchwork)
```


Define a function to custom the plot theme and annotation
```{r}
my_custom_theme <- function(plot) {
  plot +
    scale_fill_manual(
      values = c("XSHB"="#E6706E","GRAM"="#FAD272","DESE"="#F7FFCA","ENWD"="#E0E376",
                 "WTSFS"="#8FB83E","CENF"="#6B2F85","XSHB"="#E6706E",
                 "TEDE"="#005B89","CMIX"="#28B8C8","TUND"="#B03E8D")
                        ) +
    scale_x_continuous(expand = c(0,0))+
    scale_y_continuous(expand = c(0,0))+
    annotate(geom = "text", x = 34.25, y = 43.25, label = "Black Sea", fontface = "italic", color = "gray25", size = 2.3) +
    annotate(geom = "text", x = 27, y = 33.8, label = "Mediterranean Sea", fontface = "italic", color = "gray25", size = 2.3) +
    theme(
      plot.subtitle = element_text(size = 8, hjust = 0, vjust = 0),
      panel.background = element_rect(fill = "transparent", color = "transparent"),
      panel.border = element_rect(fill = "transparent", color = "black"),
      panel.grid = element_blank(),
      axis.title.y = element_text(size = 8, angle = 90),
      axis.text.y = element_text(size = 8),
      axis.ticks = element_line(size = 0.2),
      legend.key.size = unit(1.2, "mm"),
      legend.key = element_rect(fill = "transparent", color = "transparent"),
      legend.text = element_text(size = 6, margin = margin(r = -1)),
      legend.title = element_text(size = 6,hjust = 0.5,face = "bold"),
      legend.margin = margin(unit = "cm", t = 0.08, r = 0.05, b = 0.08, l = 0.05),
      legend.background = element_rect(fill = alpha("white", alpha = 0.8), size = 0.25,colour="gray20"),
      legend.position = c(0.91, 0.22)
    )
}
```


Upload required files
```{r}
land_polyg <- sf::st_read("Raster/modern_eval_land_polyg.shp")

pollen <- read.csv("Input/Pollen_data.csv") |> filter(!marine_or_velgbasin %in% c("marine","velg"))

cutpoints <- read.csv("Input/Cutpoints_optimal_umbrales.csv") |>  
  dplyr::select(biome,threshold) |> dplyr::distinct()

observed_biome <- read.csv("Input/resolution1kmfrom250m_window21km_perside.csv") |>
  dplyr::select(ID_SAMPLE,Dominant,Subdominant)

train <- read.csv("Input/BiomeData_EC4c_f.csv",header=TRUE,sep=",")

topcores_entis <- pollen |> filter(age<=150)

#Get observed dominant and subdominant biomes for each site
topcores_samples_meta <- topcores_entis |>
  dplyr::select(entity_name,latitude,longitude,ID_SAMPLE,age) |>
  distinct() |> full_join(observed_biome) |> filter(!is.na(entity_name)) 

# Create a table AllData
alldata <- pollen %>% full_join(train, by = "taxon_name") %>% filter(!is.na(ID_SAMPLE) & !is.na(Mean_CENF))
```



###Dissimilarity index
```{r}
# Dissimilarity index
biomes0 <- alldata %>%
  mutate(Epsilon = 0.5) %>%
  mutate(
    TUND_Sqrt = (taxon_percent - Mean_TUND)^2 / ((Stdev_TUND + Epsilon)^2),
    DESE_Sqrt = (taxon_percent - Mean_DESE)^2 / ((Stdev_DESE + Epsilon)^2),
    GRAM_Sqrt = (taxon_percent - Mean_GRAM)^2 / ((Stdev_GRAM + Epsilon)^2),
    XSHB_Sqrt = (taxon_percent - Mean_XSHB)^2 / ((Stdev_XSHB + Epsilon)^2),
    CENF_Sqrt = (taxon_percent - Mean_CENF)^2 / ((Stdev_CENF + Epsilon)^2),
    TEDE_Sqrt = (taxon_percent - Mean_TEDE)^2 / ((Stdev_TEDE + Epsilon)^2),
    CMIX_Sqrt = (taxon_percent - Mean_CMIX)^2 / ((Stdev_CMIX + Epsilon)^2),
    ENWD_Sqrt = (taxon_percent - Mean_ENWD)^2 / ((Stdev_ENWD + Epsilon)^2),
    WTSFS_Sqrt = (taxon_percent - Mean_WTSFS)^2 / ((Stdev_WTSFS + Epsilon)^2)
  ) %>%
  select(ID_SAMPLE, ends_with("_Sqrt")) %>%
  group_by(ID_SAMPLE) %>%
  summarise(across(ends_with("_Sqrt"), sum)) %>%
  mutate(across(ends_with("_Sqrt"), sqrt)) %>%
  ungroup()


# Similarity index
biomes <- biomes0 %>% 
  mutate(TUND=exp(-TUND_Sqrt/100)) %>% 
  mutate(DESE=exp(-DESE_Sqrt/100)) %>% 
  mutate(GRAM=exp(-GRAM_Sqrt/100)) %>% 
  mutate(XSHB=exp(-XSHB_Sqrt/100)) %>% 
  mutate(ENWD=exp(-ENWD_Sqrt/100)) %>% 
  mutate(WTSFS=exp(-WTSFS_Sqrt/100)) %>% 
  mutate(CENF=exp(-CENF_Sqrt/100)) %>% 
  mutate(CMIX=exp(-CMIX_Sqrt/100)) %>% 
  mutate(TEDE=exp(-TEDE_Sqrt/100)) %>%    
  dplyr::select(ID_SAMPLE,TUND,DESE,GRAM,XSHB,ENWD,
         WTSFS,CENF,CMIX,TEDE) 
```





```{r}
pollen_resu_all <- biomes %>%
  mutate(pred_biome = names(biomes[, 2:10])[max.col(biomes[, 2:10])]) %>%
  mutate(pred_score = apply(biomes[, 2:10], 1, max)) %>%
  inner_join(topcores_samples_meta) %>%
  group_by(entity_name, pred_biome) %>%
  add_tally(name = "samples_per_pred_biome") %>%
  mutate(sum_pred_score = sum(pred_score)) %>%
  ungroup() %>%
  select(entity_name, latitude, longitude, pred_biome, Dominant, samples_per_pred_biome, sum_pred_score, Dominant, Subdominant) %>%
  distinct() %>%
  group_by(entity_name) %>%
  slice_max(sum_pred_score) %>%
  ungroup()
```


###A comparison table nad confussion matrices
```{r}
comparison <- pollen_resu_all |>
  filter(!is.na(Dominant)) |>
  mutate(ObsComposit = coalesce(case_when(Dominant == pred_biome ~ Dominant,
                                          Subdominant == pred_biome ~ Subdominant), Dominant)) |>
  mutate(PredComposit = coalesce(case_when(Dominant == pred_biome ~ pred_biome,
                                           Subdominant == pred_biome ~ pred_biome), pred_biome))

# Define a function to compute the confusion matrix
compute_confusion_matrix <- function(data, true_col, pred_col) {
  observed <- ordered(data[[true_col]], levels = c("DESE", "XSHB", "WTSFS", "GRAM", "ENWD", "TEDE", "CMIX", "CENF", "TUND"))
  predicted <- ordered(data[[pred_col]], levels = c("DESE", "XSHB", "WTSFS", "GRAM", "ENWD", "TEDE", "CMIX", "CENF", "TUND"))
  matrix <- MLmetrics::ConfusionMatrix(y_true = observed, y_pred = predicted)
  return(matrix)
}

# Compute the confusion matrix for the Dominant data
matrix_dominant <- compute_confusion_matrix(comparison, "Dominant", "pred_biome")

# Compute the confusion matrix for the Subdominant data
comparison2 <- comparison %>% subset(!is.na(Subdominant))
matrix_subdominant <- compute_confusion_matrix(comparison2, "Subdominant", "pred_biome")

# Compute the confusion matrix for the final data (composite of dominant and subdominant)
matrix_final <- compute_confusion_matrix(comparison, "ObsComposit", "PredComposit")

# Print the matrices
matrix_dominant
matrix_subdominant

# Add a row and column of row sums and column sums
matrix_final <- rbind(matrix_final, colSums(matrix_final))
matrix_final <- cbind(matrix_final, c(rowSums(matrix_final), 0))

# Name the row and column with the epsilon symbol
rownames(matrix_final)[nrow(matrix_final)] <- "ε"
colnames(matrix_final)[ncol(matrix_final)] <- "ε"

# Add the sum of the epsilon row and epsilon column
matrix_final[nrow(matrix_final), ncol(matrix_final)] <- 63
 
matrix_final
```



```{r}
# Filter and convert to factors
comparison1 <- comparison %>%
  filter(!pred_biome %in% c("TUND", "CENF", "DESE", "XSHB"),
         !Dominant %in% c("TUND", "CENF", "DESE", "XSHB")) %>%
  mutate(across(c(pred_biome, Dominant, PredComposit, ObsComposit), as.factor))

# Metrics calculated from the comparison matrix
accuracy_metrics <- comparison1 %>%
  summarize(
    acc1 = mlr3measures::acc(Dominant, pred_biome),
    acc2 = mlr3measures::acc(ObsComposit, PredComposit),
    bacc1 = mlr3measures::bacc(Dominant, pred_biome),
    bacc2 = mlr3measures::bacc(ObsComposit, PredComposit)
  )

# A dataframe of the accuracy and balanced accuracy
metrics <- data.frame(
  Test_Data = c("EMBSE", "EMBSE"),
  Evaluation = c("Dominant", "Composit"),
  Accuracy = c(accuracy_metrics$acc1 * 100, accuracy_metrics$acc2 * 100),
  Balanced_accuracy = c(accuracy_metrics$bacc1 * 100, accuracy_metrics$bacc2 * 100)
)

metrics
```



```{r}
plot_observed <- ggplot() +
  geom_sf(data=land_polyg, fill="#e8e8e8", color="gray65",lwd=0, alpha=1) +
  geom_point(data=comparison,aes(x=longitude,y=latitude, fill=Dominant),shape=21,size=2,stroke=0.08,linetype="dotted",color="gray30") +
  labs(x=NULL,y=NULL,fill="Biome")+
  geom_text(aes(x = 57.5, y = 47.6, label = "(a)"), size = 3.25, fontface = "bold") 

plot_observed <- my_custom_theme(plot_observed)


plot_predicted <- ggplot() +
  geom_sf(data=land_polyg, fill="#e8e8e8", color="#A6A6A6",lwd=0.4, alpha=1) +
  geom_point(data=comparison,aes(x=longitude,y=latitude, fill=pred_biome),shape=21,size=1.8,stroke=0.4,linetype="dotted",color="gray30",show.legend = F) +
  labs(x=NULL,y=NULL) +
  geom_text(aes(x = 57.5, y = 47.6, label = "(b)"), size = 3.25, fontface = "bold") 

plot_predicted <- my_custom_theme(plot_predicted)
 
plot_observed
plot_predicted
```


```{r}
plot_observed <- plot_observed + theme(axis.text.x = element_blank(),
                               axis.title.x = element_blank())

plot_predicted <- plot_predicted + theme(axis.text.x = element_text(size=8),
                               axis.title.x = element_text(size=8)) 

final_plot <- (plot_observed / plot_predicted)

# Print the combined plot
final_plot
```


```{r}
ggsave(plot = final_plot, filename = "Output/Figure_2.pdf", units = "cm", width = 8, height = 10)
```


