---
title: "Figure_5"
output: html_document
date: "2023-10-31"
---


```{r}
library(tidyverse)
```


Theme for the plots
```{r}
my_theme <- theme(
  panel.border = element_rect(fill="transparent",colour="black",size=0.3),
  panel.background = element_rect(fill="transparent",colour="transparent"),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.text.y = element_text(size=8),
  axis.title.y = element_text(size=8),
  axis.text.x = element_text(size=8),
  axis.title.x = element_text(size=8),
  plot.title = element_text(size=8, vjust=-1),
  plot.subtitle = element_text(size=8,vjust=-1)
  )
```



```{r}
train <- read.csv("Input/BiomeData_EC4c_f.csv",header=TRUE,sep=",")

cutpoints <- read.csv("Input/Cutpoints_optimal_umbrales.csv") |>  
  dplyr::select(biome,threshold) |> 
  dplyr::distinct()

pollen <- read.csv("Input/Pollen_data.csv") |>
  filter(!marine_or_velgbasin %in% c("marine","velg"))

pollen_metadat <- pollen |>
  select(entity_name,ID_SAMPLE,age,avg_depth,latitude,longitude,elevation) |>
  distinct()

# Create a table AllData
alldata <- pollen %>% full_join(train, by = "taxon_name") %>% filter(!is.na(ID_SAMPLE) & !is.na(Mean_CENF))
```


```{r}
# Dissimilarity index
biomes0 <- alldata %>%
  mutate(Epsilon = 0.5) %>%
  mutate(
    TUND_Sqrt = (taxon_percent - Mean_TUND)^2 / ((Stdev_TUND + Epsilon)^2),
    DESE_Sqrt = (taxon_percent - Mean_DESE)^2 / ((Stdev_DESE + Epsilon)^2),
    GRAM_Sqrt = (taxon_percent - Mean_GRAM)^2 / ((Stdev_GRAM + Epsilon)^2),
    XSHB_Sqrt = (taxon_percent - Mean_XSHB)^2 / ((Stdev_XSHB + Epsilon)^2),
    CENF_Sqrt = (taxon_percent - Mean_CENF)^2 / ((Stdev_CENF + Epsilon)^2),
    TEDE_Sqrt = (taxon_percent - Mean_TEDE)^2 / ((Stdev_TEDE + Epsilon)^2),
    CMIX_Sqrt = (taxon_percent - Mean_CMIX)^2 / ((Stdev_CMIX + Epsilon)^2),
    ENWD_Sqrt = (taxon_percent - Mean_ENWD)^2 / ((Stdev_ENWD + Epsilon)^2),
    WTSFS_Sqrt = (taxon_percent - Mean_WTSFS)^2 / ((Stdev_WTSFS + Epsilon)^2)
  ) %>%
  select(ID_SAMPLE, ends_with("_Sqrt")) %>%
  group_by(ID_SAMPLE) %>%
  summarise(across(ends_with("_Sqrt"), sum)) %>%
  mutate(across(ends_with("_Sqrt"), sqrt)) %>%
  ungroup()


# Get reciprocal of the scores and perform normalization
biomes <- biomes0 %>%
  mutate(across(ends_with("_Sqrt"), ~ exp(-. / 100))) |>
  rename_with(~str_remove(., "_Sqrt"), ends_with("_Sqrt")) 
```



```{r}
polenpred <- biomes |>
  tidyr::pivot_longer(cols = TUND:WTSFS, names_to = "pred_biome", values_to = "pred_score") |>
  group_by(ID_SAMPLE) |>
  arrange(ID_SAMPLE,desc(pred_score)) |>
  slice_max(pred_score, n=1) |>
  ungroup() |>
  inner_join(cutpoints, by =  c("pred_biome" = "biome")) |> 
  mutate(pred_biome_noa = case_when(pred_score <= threshold ~ "NONA", TRUE ~ pred_biome)) |> 
  inner_join(pollen_metadat, by = "ID_SAMPLE")|>
  dplyr::select(entity_name,latitude,longitude,elevation,ID_SAMPLE,age,everything()) |>
  mutate(age = age/1000)
```


```{r}
tabla <- seq(7, 4, -0.5) %>%
  map_dfr(function(i) {
    ventana <- 0.15
    centro <- i

    age_min <- centro - ventana
    age_max <- centro + ventana

    polenpred %>%
      filter(age > age_min & age <= age_max) %>%
      group_by(entity_name, pred_biome_noa) %>%
      add_tally(name = "samples_per_pred_biome") %>%
      mutate(sum_pred_score = sum(pred_score)) %>%
      ungroup() %>%
      select(entity_name, latitude, longitude, pred_biome_noa, samples_per_pred_biome, sum_pred_score) %>%
      distinct() %>%
      arrange(entity_name, desc(sum_pred_score)) %>%
      group_by(entity_name) %>%
      slice_max(samples_per_pred_biome, with_ties = FALSE) %>%
      ungroup() %>%
      add_tally(name = "total_sites") %>%
      group_by(pred_biome_noa) %>%
      add_tally() %>%
      ungroup() %>%
      select(pred_biome_noa, total_sites, n) %>%
      distinct() %>%
      mutate(percent_records = (n / total_sites) * 100, bincentre = i)
  }) %>%
  bind_rows()

```



```{r}
plot_hist <- tabla |>
  filter(pred_biome_noa=="TEDE") |>
  ggplot(aes(x=bincentre,y=percent_records))+
  geom_bar(stat = "identity", colour="#00625d",fill="#00625d") +
  scale_x_continuous(breaks = seq(4,7,0.5),expand = c(0.01,0.01)) +
  scale_y_continuous(expand = c(0.01,0.1)) +
  labs(x="Age (ky)", y="Records (%)") +
  my_theme

plot_hist
```

```{r}
ggsave(plot = plot_hist, filename = "Output/Figure_5.pdf", units = "cm", height = 6,width = 8.3)
```

