---
title: "Mapas nuevos"
output: html_document
---


```{r}
library(tidyverse)
library(patchwork)
```



```{r}
tema_plots <- theme(plot.title=element_text(size=8, vjust=-1),
        plot.subtitle=element_text(size=8,vjust=-1),
        plot.margin = unit(c(0.3,0.3,0.3,0.3),"cm"),
            panel.grid = element_blank(),
            panel.background = element_rect(color="transparent", fill="transparent"),
            panel.border = element_rect(fill = "transparent",color="black",linewidth =0.4),
            axis.title.y = element_blank(),
            axis.title.x = element_blank(),
            axis.text.x = element_text(size=8),
            axis.text.y = element_text(size=8),
            legend.text = element_text(size = 6),
            legend.key.height  = unit(3, "mm"),
            legend.key.width  = unit(1, "mm"),
            legend.key = element_rect(fill = "transparent",color="transparent"),
            legend.title = element_text(size = 6),
            legend.spacing = unit(1,"mm"),
            legend.margin = margin(unit = "cm", t=0,r=0.08,b=0.09,l=0.08),
            legend.background = element_rect(fill="transparent",color="gray30",linewidth=0.25),
            legend.position = c(0.846,0.146))
```




```{r}
land_polyg <- sf::st_read("Raster/modern_eval_land_polyg.shp")

pollen <- read.csv("Input/Pollen_data.csv") |> 
  filter(!marine_or_velgbasin %in% c("marine","velg"))

cutpoints <- read.csv("Input/Cutpoints_optimal_umbrales.csv") |>  
  dplyr::select(biome,threshold) |> dplyr::distinct()

observed_biome <- read.csv("Input/resolution1kmfrom250m_window21km_perside.csv") |>
  dplyr::select(ID_SAMPLE,Dominant,Subdominant)

train <- read.csv("Input/BiomeData_EC4c_f.csv",header=TRUE,sep=",")

pollen_sampmeta <- pollen |>
  dplyr::select(entity_name,latitude,longitude,elevation,ID_SAMPLE,age) |> distinct()

# Create a table AllData
alldata <- pollen %>% full_join(train, by = "taxon_name") %>% filter(!is.na(ID_SAMPLE) & !is.na(Mean_CENF))
```


###Dissimilarity index
```{r}
# Dissimilarity index
biomes0 <- alldata %>%
  mutate(Epsilon = 0.5) %>%
  mutate(
    TUND_Sqrt = (taxon_percent - Mean_TUND)^2 / ((Stdev_TUND + Epsilon)^2),
    DESE_Sqrt = (taxon_percent - Mean_DESE)^2 / ((Stdev_DESE + Epsilon)^2),
    GRAM_Sqrt = (taxon_percent - Mean_GRAM)^2 / ((Stdev_GRAM + Epsilon)^2),
    XSHB_Sqrt = (taxon_percent - Mean_XSHB)^2 / ((Stdev_XSHB + Epsilon)^2),
    CENF_Sqrt = (taxon_percent - Mean_CENF)^2 / ((Stdev_CENF + Epsilon)^2),
    TEDE_Sqrt = (taxon_percent - Mean_TEDE)^2 / ((Stdev_TEDE + Epsilon)^2),
    CMIX_Sqrt = (taxon_percent - Mean_CMIX)^2 / ((Stdev_CMIX + Epsilon)^2),
    ENWD_Sqrt = (taxon_percent - Mean_ENWD)^2 / ((Stdev_ENWD + Epsilon)^2),
    WTSFS_Sqrt = (taxon_percent - Mean_WTSFS)^2 / ((Stdev_WTSFS + Epsilon)^2)
  ) %>%
  select(ID_SAMPLE, ends_with("_Sqrt")) %>%
  group_by(ID_SAMPLE) %>%
  summarise(across(ends_with("_Sqrt"), sum)) %>%
  mutate(across(ends_with("_Sqrt"), sqrt)) %>%
  ungroup()

```


###Get recirpocal of the scores and normalization
```{r}
biomes <- biomes0 %>% 
  mutate(TUND=exp(-TUND_Sqrt/100)) %>% 
  mutate(DESE=exp(-DESE_Sqrt/100)) %>% 
  mutate(GRAM=exp(-GRAM_Sqrt/100)) %>% 
  mutate(XSHB=exp(-XSHB_Sqrt/100)) %>% 
  mutate(ENWD=exp(-ENWD_Sqrt/100)) %>% 
  mutate(WTSFS=exp(-WTSFS_Sqrt/100)) %>% 
  mutate(CENF=exp(-CENF_Sqrt/100)) %>% 
  mutate(CMIX=exp(-CMIX_Sqrt/100)) %>% 
  mutate(TEDE=exp(-TEDE_Sqrt/100)) %>%    
  dplyr::select(ID_SAMPLE,TUND,DESE,GRAM,XSHB,ENWD,
         WTSFS,CENF,CMIX,TEDE) 
```


```{r}
polenpred <- biomes |>
  tidyr::pivot_longer(cols = TUND:TEDE, names_to = "pred_biome", values_to = "pred_score") |>
  group_by(ID_SAMPLE) |>
  arrange(ID_SAMPLE,desc(pred_score)) |>
  slice_max(pred_score, n=1) |>
  ungroup() |>
  inner_join(cutpoints, by =  c("pred_biome" = "biome")) |> 
  mutate(pred_biome_noa = case_when(pred_score <= threshold ~ "NONA", TRUE ~ pred_biome)) |> 
  inner_join(pollen_sampmeta, by = "ID_SAMPLE") |>
  dplyr::select(entity_name,latitude,longitude,elevation,ID_SAMPLE,age,everything()) |>
  mutate(age = age/1000)
  
 # dplyr::select(-elevation)
```




```{r}
plot_list <- list()
for (i in seq(8,4,-0.5)) {

ventana <- 0.15
centro_oldest <- i
centro_youngest <- centro_oldest - 0.5
  
age_min_oldest <- centro_oldest - ventana
age_max_oldest <- centro_oldest + ventana

age_min_youngest <- centro_youngest - ventana
age_max_youngest <- centro_youngest  + ventana

#Get the predicted biome within the window
oldest_period <- polenpred |>
  filter(age>=age_min_oldest & age <=age_max_oldest) |> 
  group_by(entity_name,pred_biome_noa) |>
  add_tally(name = "samples_per_pred_biome") |>
  mutate(sum_pred_score = sum(pred_score)) |>
  ungroup() |>
  dplyr::select(entity_name,latitude,longitude,pred_biome_noa,samples_per_pred_biome,sum_pred_score) |>
  distinct() |>
  arrange(entity_name,desc(sum_pred_score)) |>
  group_by(entity_name) |>
  slice_max(samples_per_pred_biome, with_ties = F) |>
  ungroup() |>
  mutate(period = "oldest_p")

#Get the predicted biome within the window
youngest_period <- polenpred |>
  filter(age>age_min_youngest & age <=age_max_youngest) |> 
  group_by(entity_name,pred_biome_noa) |>
  add_tally(name = "samples_per_pred_biome") |>
  mutate(sum_pred_score = sum(pred_score)) |>
  ungroup() |>
  dplyr::select(entity_name,latitude,longitude,pred_biome_noa,samples_per_pred_biome,sum_pred_score) |>
  distinct() |>
  arrange(entity_name,desc(sum_pred_score)) |>
  group_by(entity_name) |>
  slice_max(samples_per_pred_biome, with_ties = F) |>
  ungroup() |>
  mutate(period = "youngest_p")

#Put together both periods for comparison
both_tede <- bind_rows(youngest_period,oldest_period)

#To filter the entities that exist for the two periods and make a biome comparison table between the two periods (the youngest vs the oldest) to establish the different cases
both_tede_case1 <- both_tede |>
  group_by(entity_name) |>
  add_tally() |> ungroup() |>
  filter(n > 1) |>
  group_by(entity_name) |>
  mutate(youngest_biome= lag(pred_biome_noa)) |>
  ungroup() |>
  filter(!is.na(youngest_biome)) |>
  rename(oldest_biome = pred_biome_noa) |>
  mutate(youngest_biome = case_when(youngest_biome=="TEDE"~"TEDE",TRUE~"non-TEDE"),
         oldest_biome = case_when(oldest_biome=="TEDE"~"TEDE",TRUE~"non-TEDE")) |>
  mutate(case1=case_when((youngest_biome=="TEDE" & oldest_biome == "TEDE" ) ~ "change from TEDE"),
         case2=case_when((youngest_biome=="TEDE" & oldest_biome != "TEDE") ~ "change to TEDE"),
         final_case=case_when(!is.na(case1) ~ case1,
                              !is.na(case2) ~ case2, TRUE ~ "non-TEDE"))



#To filter the entities that exist for only one of the two periods
both_tede1_allsamples <- both_tede_case1 |> dplyr::select(entity_name) |> pull()

youngest_only_one_window <- youngest_period |>
  filter(!entity_name%in%both_tede1_allsamples) |>
  mutate(new_tede = case_when(pred_biome_noa=="TEDE" ~ "TEDE", TRUE ~ "non-TEDE"))

oldest_only_one_window <- oldest_period |>
  filter(!entity_name%in%both_tede1_allsamples)


#Plot time
map_youngest <- ggplot() +
  geom_sf(data=land_polyg, fill="gray88", color="gray75",lwd=0.2, alpha=1) +
  
  geom_point(data = both_tede_case1, aes(x=longitude,y=latitude,fill=final_case,size=final_case),shape=21,color="#262836",stroke=0.2) +
  
  geom_point(data = youngest_only_one_window, aes(x=longitude,y=latitude, fill=new_tede,size=new_tede),shape=21, color="#262836",stroke=0.2) +
  
  scale_fill_manual(values =c("change to TEDE"="#00625d","TEDE"="#7fbc42","change from TEDE"="#bf6404","non-TEDE"="white")) +
  scale_size_manual(values =c("change to TEDE"=1.8,"TEDE"=1.8,"change from TEDE"=1.8,"non-TEDE"=0.8)) +
  scale_x_continuous(expand = c(0,0))+
  scale_y_continuous(expand = c(0,0))+
  guides(fill = FALSE, size=FALSE) +
  annotate("text", x = 50.9, y = 47.85, label = paste(centro_youngest,"±",ventana,sep = ""),size=3) +
  labs(x=NULL, y=NULL,color=NULL, shape=NULL) +
  tema_plots


  # Add the map to the plot list
  plot_list[[length(plot_list) + 1]] <- map_youngest
}

# Arrange the individual plots into a single plot
final_plot <- wrap_plots(plotlist = plot_list, ncol = 2)  # Adjust ncol as needed

# Display the final plot
print(final_plot)
```


```{r}
ggsave(plot = final_plot,filename = "Output/Figure_6.pdf", units = "cm", width = 16, height = 21)

```

